### PR TITLE
contact.txt

### PR DESCRIPTION
**Pull request by arpan-lol**

### CODE REVIEW

**Comment by arpan-lol** [comment]
please see the contents of the file I created.

**Comment by jeanfbrito** [comment]
If you want to be contacted, you need to provide an address of email or something. What do you need?

**Comment by arpan-lol** [comment]
Is Discord fine? Im MasterMind#6098 if yes.

**Comment by jeanfbrito** [comment]
Nope. I don't use discord. Send an email to ***@***.***

Em seg, 12 de jul de 2021 09:51, Arpan ***@***.***> escreveu:

**Comment by arpan-lol** [comment]
Github blurred out the e-mail address. Is it the one in your profile?

**Comment by jeanfbrito** [comment]
Yeah, use that from my profile.

Em seg, 12 de jul de 2021 23:33, Arpan ***@***.***> escreveu:

**Pull request closed without merging**
